import { MenuItem } from './types';

export const menuData: MenuItem[] = [
  {
    id: 'hamburger',
    name: 'Гамбургер',
    price: 89,
    category: 'burgers',
    description: 'Классический бургер с сочной котлетой и фирменным соусом. Идеально для быстрого перекуса.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический'],
    protein: 15,
    fat: 12,
    carbs: 32,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/baf7a3f6-ceac-47dc-8f31-ac7230ddf3b4.jpg',
  },
  {
    id: 'cheeseburger',
    name: 'Чизбургер',
    price: 109,
    category: 'burgers',
    description: 'Гамбургер с добавлением нежного сыра. Насыщенный вкус для настоящих любителей сыра.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический', 'Один ломтик сыра'],
    protein: 18,
    fat: 15,
    carbs: 33,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/85d19cf8-8f68-4896-a331-a9a2a91e0264.jpg',
  },
  {
    id: 'chickenburger',
    name: 'Чикенбургер',
    price: 119,
    category: 'burgers',
    description: 'Бургер с хрустящей куриной котлетой и свежим листом салата. Легкий и сочный вариант.',
    ingredients: ['Две булочки', 'Котлета куриная', 'Соус классический', 'Лист салата'],
    protein: 20,
    fat: 10,
    carbs: 35,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/db9ef92a-8405-418e-827f-ae62acf2930b.jpg',
  },
  {
    id: 'fartburger',
    name: 'Фартбургер',
    price: 199,
    category: 'burgers',
    description: 'Наш фирменный бургер! Сочная котлета, свежие овощи и секретный соус делают его незабываемым.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический', 'Лист салата', 'Три кусочка огурчика', 'Два ломтика помидора'],
    protein: 22,
    fat: 18,
    carbs: 38,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/1eaf9bc3-b7ae-42a6-b259-5a6a9d1bcfac.jpg',
  },
  {
    id: 'fartburger-chicken',
    name: 'Фартбургер куриный',
    price: 199,
    category: 'burgers',
    description: 'Легкая версия фирменного бургера с куриной котлетой. Все та же свежесть и вкус!',
    ingredients: ['Две булочки', 'Котлета куриная', 'Соус классический', 'Лист салата', 'Три кусочка огурчика', 'Два ломтика помидора'],
    protein: 25,
    fat: 12,
    carbs: 40,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/30d3c1c6-552d-41cb-94f0-c47a34ac9337.jpg',
  },
  {
    id: 'fries',
    name: 'Картофель фри',
    price: 99,
    category: 'snacks',
    description: 'Хрустящая золотистая картошка, жаренная во фритюре до идеального состояния.',
    ingredients: ['Картошка жареная во фритюре'],
    protein: 3,
    fat: 15,
    carbs: 35,
    options: [
      {
        type: 'size',
        choices: [
          { label: 'Маленькая', price: 99 },
          { label: 'Средняя', price: 139 },
          { label: 'Большая', price: 199 },
          { label: 'Огромная', price: 299 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/cd7160bf-99ea-478a-9b12-28b96c153398.jpg',
  },
  {
    id: 'nuggets',
    name: 'Наггетсы',
    price: 99,
    category: 'snacks',
    description: 'Нежное куриное филе в хрустящей панировке. Отличная закуска для любого случая.',
    ingredients: ['Куриное филе'],
    protein: 18,
    fat: 12,
    carbs: 20,
    options: [
      {
        type: 'count',
        choices: [
          { label: '3шт', price: 99 },
          { label: '6шт', price: 179 },
          { label: '9шт', price: 249 },
          { label: '20шт', price: 479 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/0a098a95-8ad8-451f-8c4e-e9eb3241db9b.jpg',
  },
  {
    id: 'pancakes',
    name: 'Блины',
    price: 99,
    category: 'desserts',
    description: 'Традиционные блины с неожиданной изюминкой. Нежные, тающие во рту.',
    ingredients: ['Самые обычные блины с изюминкой'],
    protein: 8,
    fat: 10,
    carbs: 45,
    options: [
      {
        type: 'filling',
        choices: [
          { label: 'С шоколадом', price: 0 },
          { label: 'С маслом', price: 0 },
          { label: 'С ветчиной и сыром', price: 0 },
        ],
      },
      {
        type: 'count',
        choices: [
          { label: '1шт', price: 99 },
          { label: '3шт', price: 259 },
          { label: '5шт', price: 399 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/2babe74c-90cf-4e13-8e9f-ff3eecf07c66.jpg',
  },
  {
    id: 'icecream',
    name: 'Мороженое',
    price: 119,
    category: 'desserts',
    description: 'Натуральное мороженое высшего качества. Освежающий десерт на любой вкус.',
    ingredients: ['Самое обычное мороженое'],
    protein: 4,
    fat: 8,
    carbs: 25,
    options: [
      {
        type: 'flavor',
        choices: [
          { label: 'Малиновое', price: 139 },
          { label: 'Шоколадное', price: 149 },
          { label: 'Пломбир', price: 129 },
          { label: 'С орехами', price: 119 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/58081753-5fcb-4cfe-8f5d-4cef244a53d3.jpg',
  },
  {
    id: 'milkshake',
    name: 'МилкШейк',
    price: 129,
    category: 'desserts',
    description: 'Густой охлажденный коктейль из молока и мороженого. Идеальное дополнение к еде.',
    ingredients: ['холодный и густой коктейль из молока и мороженого'],
    protein: 6,
    fat: 12,
    carbs: 35,
    options: [
      {
        type: 'flavor',
        choices: [
          { label: 'Малиновый', price: 139 },
          { label: 'Шоколадный', price: 159 },
          { label: 'Пломбир', price: 129 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/1ef4b039-4ca8-4622-8992-5a49706141cd.jpg',
  },
  {
    id: 'coffee',
    name: 'Кофе',
    price: 99,
    category: 'drinks',
    description: 'Ароматный кофе из свежеобжаренных зерен. Бодрящий напиток для продуктивного дня.',
    ingredients: ['Состав зависит от вида кофе'],
    protein: 2,
    fat: 3,
    carbs: 5,
    options: [
      {
        type: 'type',
        choices: [
          { label: 'Латте', price: 0 },
          { label: 'Эспрессо', price: 0 },
          { label: 'Американо', price: 0 },
          { label: 'Флет Уайт', price: 0 },
          { label: 'Горячий шоколад', price: 0 },
          { label: 'Какао', price: 0 },
          { label: 'Раф', price: 0 },
          { label: 'Мокко', price: 0 },
        ],
      },
      {
        type: 'size',
        choices: [
          { label: 'Маленький', price: 99 },
          { label: 'Средний', price: 139 },
          { label: 'Большой', price: 179 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/86ccc59d-7f6e-48f8-aa62-a5ed438323b0.jpg',
  },
  {
    id: 'tea',
    name: 'Чай',
    price: 99,
    category: 'drinks',
    description: 'Отборный рассыпной чай высшего сорта. Традиционный напиток для души и тела.',
    ingredients: ['Чай рассыпной'],
    protein: 0,
    fat: 0,
    carbs: 2,
    options: [
      {
        type: 'type',
        choices: [
          { label: 'Зелёный', price: 0 },
          { label: 'Чёрный', price: 0 },
        ],
      },
      {
        type: 'size',
        choices: [
          { label: 'Маленький', price: 99 },
          { label: 'Средний', price: 129 },
          { label: 'Большой', price: 159 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/58268df4-a7a6-46b8-8022-4a1d69a81270.jpg',
  },
  {
    id: 'cola',
    name: 'Кока кола',
    price: 79,
    category: 'drinks',
    description: 'Оригинальная Coca-Cola с неповторимым вкусом. Освежает и бодрит в любое время.',
    ingredients: ['Оригинальная Кока кола'],
    protein: 0,
    fat: 0,
    carbs: 42,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 79 },
          { label: '0.8л', price: 99 },
          { label: '1.0л', price: 119 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В пластиковой бутылке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/2d5e9272-858d-42b2-b297-7c47a6925690.jpg',
  },
  {
    id: 'juice',
    name: 'Сок',
    price: 99,
    category: 'drinks',
    description: 'Свежевыжатый сок из натуральных фруктов. Витамины и польза в каждом глотке.',
    ingredients: ['Свежевыжатый сок'],
    protein: 1,
    fat: 0,
    carbs: 25,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 99 },
          { label: '0.8л', price: 149 },
          { label: '1.0л', price: 189 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В картонной коробке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/fec51fbe-c5b1-4004-b899-059d38590f43.jpg',
  },
  {
    id: 'water',
    name: 'Вода',
    price: 49,
    category: 'drinks',
    description: 'Чистая питьевая вода высшего качества. Основа здоровья и жизни.',
    ingredients: ['Питьевая вода'],
    protein: 0,
    fat: 0,
    carbs: 0,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 49 },
          { label: '0.8л', price: 69 },
          { label: '1.0л', price: 89 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В пластиковой бутылке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/80742102-34b1-430a-9a14-2657fdc7722c.jpg',
  },
  {
    id: 'mashed-potatoes',
    name: 'Пюре с котлетой',
    price: 159,
    category: 'special',
    description: 'Домашнее нежное пюре с сочной котлетой. Комфортная еда, как дома.',
    ingredients: ['Котлета'],
    protein: 18,
    fat: 15,
    carbs: 42,
    imageUrl: 'https://cdn.poehali.dev/projects/8e76fad1-d204-4465-b35f-8365569acbaa/files/48203da9-d7a2-4e30-a1a9-99ab05ada98f.jpg',
  },
];