import { MenuItem } from './types';

export const menuData: MenuItem[] = [
  {
    id: 'hamburger',
    name: 'Гамбургер',
    price: 89,
    category: 'burgers',
    description: 'Классический бургер с сочной котлетой и фирменным соусом. Идеально для быстрого перекуса.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический'],
    protein: 15,
    fat: 12,
    carbs: 32,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
  },
  {
    id: 'cheeseburger',
    name: 'Чизбургер',
    price: 109,
    category: 'burgers',
    description: 'Гамбургер с добавлением нежного сыра. Насыщенный вкус для настоящих любителей сыра.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический', 'Один ломтик сыра'],
    protein: 18,
    fat: 15,
    carbs: 33,
    imageUrl: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400',
  },
  {
    id: 'chickenburger',
    name: 'Чикенбургер',
    price: 119,
    category: 'burgers',
    description: 'Бургер с хрустящей куриной котлетой и свежим листом салата. Легкий и сочный вариант.',
    ingredients: ['Две булочки', 'Котлета куриная', 'Соус классический', 'Лист салата'],
    protein: 20,
    fat: 10,
    carbs: 35,
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400',
  },
  {
    id: 'fartburger',
    name: 'Фартбургер',
    price: 199,
    category: 'burgers',
    description: 'Наш фирменный бургер! Сочная котлета, свежие овощи и секретный соус делают его незабываемым.',
    ingredients: ['Две булочки', 'Котлета говяжья', 'Соус классический', 'Лист салата', 'Три кусочка огурчика', 'Два ломтика помидора'],
    protein: 22,
    fat: 18,
    carbs: 38,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
  },
  {
    id: 'fartburger-chicken',
    name: 'Фартбургер куриный',
    price: 199,
    category: 'burgers',
    description: 'Легкая версия фирменного бургера с куриной котлетой. Все та же свежесть и вкус!',
    ingredients: ['Две булочки', 'Котлета куриная', 'Соус классический', 'Лист салата', 'Три кусочка огурчика', 'Два ломтика помидора'],
    protein: 25,
    fat: 12,
    carbs: 40,
    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400',
  },
  {
    id: 'fries',
    name: 'Картофель фри',
    price: 99,
    category: 'snacks',
    description: 'Хрустящая золотистая картошка, жаренная во фритюре до идеального состояния.',
    ingredients: ['Картошка жареная во фритюре'],
    protein: 3,
    fat: 15,
    carbs: 35,
    options: [
      {
        type: 'size',
        choices: [
          { label: 'Маленькая', price: 99 },
          { label: 'Средняя', price: 139 },
          { label: 'Большая', price: 199 },
          { label: 'Огромная', price: 299 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
  },
  {
    id: 'nuggets',
    name: 'Наггетсы',
    price: 99,
    category: 'snacks',
    description: 'Нежное куриное филе в хрустящей панировке. Отличная закуска для любого случая.',
    ingredients: ['Куриное филе'],
    protein: 18,
    fat: 12,
    carbs: 20,
    options: [
      {
        type: 'count',
        choices: [
          { label: '3шт', price: 99 },
          { label: '6шт', price: 179 },
          { label: '9шт', price: 249 },
          { label: '20шт', price: 479 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
  },
  {
    id: 'pancakes',
    name: 'Блины',
    price: 99,
    category: 'desserts',
    description: 'Традиционные блины с неожиданной изюминкой. Нежные, тающие во рту.',
    ingredients: ['Самые обычные блины с изюминкой'],
    protein: 8,
    fat: 10,
    carbs: 45,
    options: [
      {
        type: 'filling',
        choices: [
          { label: 'С шоколадом', price: 0 },
          { label: 'С маслом', price: 0 },
          { label: 'С ветчиной и сыром', price: 0 },
        ],
      },
      {
        type: 'count',
        choices: [
          { label: '1шт', price: 99 },
          { label: '3шт', price: 259 },
          { label: '5шт', price: 399 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400',
  },
  {
    id: 'icecream',
    name: 'Мороженое',
    price: 119,
    category: 'desserts',
    description: 'Натуральное мороженое высшего качества. Освежающий десерт на любой вкус.',
    ingredients: ['Самое обычное мороженое'],
    protein: 4,
    fat: 8,
    carbs: 25,
    options: [
      {
        type: 'flavor',
        choices: [
          { label: 'Малиновое', price: 139 },
          { label: 'Шоколадное', price: 149 },
          { label: 'Пломбир', price: 129 },
          { label: 'С орехами', price: 119 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
  },
  {
    id: 'milkshake',
    name: 'МилкШейк',
    price: 129,
    category: 'desserts',
    description: 'Густой охлажденный коктейль из молока и мороженого. Идеальное дополнение к еде.',
    ingredients: ['холодный и густой коктейль из молока и мороженого'],
    protein: 6,
    fat: 12,
    carbs: 35,
    options: [
      {
        type: 'flavor',
        choices: [
          { label: 'Малиновый', price: 139 },
          { label: 'Шоколадный', price: 159 },
          { label: 'Пломбир', price: 129 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
  },
  {
    id: 'coffee',
    name: 'Кофе',
    price: 99,
    category: 'drinks',
    description: 'Ароматный кофе из свежеобжаренных зерен. Бодрящий напиток для продуктивного дня.',
    ingredients: ['Состав зависит от вида кофе'],
    protein: 2,
    fat: 3,
    carbs: 5,
    options: [
      {
        type: 'type',
        choices: [
          { label: 'Латте', price: 0 },
          { label: 'Эспрессо', price: 0 },
          { label: 'Американо', price: 0 },
          { label: 'Флет Уайт', price: 0 },
          { label: 'Горячий шоколад', price: 0 },
          { label: 'Какао', price: 0 },
          { label: 'Раф', price: 0 },
          { label: 'Мокко', price: 0 },
        ],
      },
      {
        type: 'size',
        choices: [
          { label: 'Маленький', price: 99 },
          { label: 'Средний', price: 139 },
          { label: 'Большой', price: 179 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400',
  },
  {
    id: 'tea',
    name: 'Чай',
    price: 99,
    category: 'drinks',
    description: 'Отборный рассыпной чай высшего сорта. Традиционный напиток для души и тела.',
    ingredients: ['Чай рассыпной'],
    protein: 0,
    fat: 0,
    carbs: 2,
    options: [
      {
        type: 'type',
        choices: [
          { label: 'Зелёный', price: 0 },
          { label: 'Чёрный', price: 0 },
        ],
      },
      {
        type: 'size',
        choices: [
          { label: 'Маленький', price: 99 },
          { label: 'Средний', price: 129 },
          { label: 'Большой', price: 159 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
  },
  {
    id: 'cola',
    name: 'Кока кола',
    price: 79,
    category: 'drinks',
    description: 'Оригинальная Coca-Cola с неповторимым вкусом. Освежает и бодрит в любое время.',
    ingredients: ['Оригинальная Кока кола'],
    protein: 0,
    fat: 0,
    carbs: 42,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 79 },
          { label: '0.8л', price: 99 },
          { label: '1.0л', price: 119 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В пластиковой бутылке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
  },
  {
    id: 'juice',
    name: 'Сок',
    price: 99,
    category: 'drinks',
    description: 'Свежевыжатый сок из натуральных фруктов. Витамины и польза в каждом глотке.',
    ingredients: ['Свежевыжатый сок'],
    protein: 1,
    fat: 0,
    carbs: 25,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 99 },
          { label: '0.8л', price: 149 },
          { label: '1.0л', price: 189 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В картонной коробке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
  },
  {
    id: 'water',
    name: 'Вода',
    price: 49,
    category: 'drinks',
    description: 'Чистая питьевая вода высшего качества. Основа здоровья и жизни.',
    ingredients: ['Питьевая вода'],
    protein: 0,
    fat: 0,
    carbs: 0,
    options: [
      {
        type: 'volume',
        choices: [
          { label: '0.5л', price: 49 },
          { label: '0.8л', price: 69 },
          { label: '1.0л', price: 89 },
        ],
      },
      {
        type: 'container',
        choices: [
          { label: 'В стакане', price: 0 },
          { label: 'В пластиковой бутылке', price: 0 },
          { label: 'В стеклянной бутылке', price: 10 },
        ],
      },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400',
  },
  {
    id: 'mashed-potatoes',
    name: 'Пюре с котлетой',
    price: 159,
    category: 'special',
    description: 'Домашнее нежное пюре с сочной котлетой. Комфортная еда, как дома.',
    ingredients: ['Домашнее вкусное пюре с котлетой'],
    protein: 18,
    fat: 15,
    carbs: 42,
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
  },
];
